### ISSUE TITLE
Logging sometimes does not work

### ISSUE THREAD

**Issue by phpstudyone** [AuthorizeNet/sdk-php#306] opened 2018-03-30 04:29 UTC
I requested  [Create Customer Payment Profile](https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-payment-profile)  twice. But the two log contents are inconsistent. 

The first time there is response data:

![image](https://user-images.githubusercontent.com/11455285/38124615-aa0bbc78-3415-11e8-8435-876d0e62b65b.png)

The second time there is no:
![image](https://user-images.githubusercontent.com/11455285/38124636-c6c90e1a-3415-11e8-8c8c-331338ccd25f.png)

**Both requests return the correct data**

**Comment by ashtru** [comment] 2018-03-31 05:28
Thanks for raising the issue @phpstudyOne . We are looking into it.

**Comment by ashtru** [comment] 2018-07-12 15:01
Unable to reproduce this issue.
@phpstudyone , if you are still getting this error or something similar, can you share more more details on the CreateCustomerProfile request, for which the GetCustomerProfile response doesn't appear in the log?

**Comment by chsriniv9** [comment] 2018-08-07 13:24
Closing this issue as we don't have enough details to root cause for any resolution. Please feel free to re-open if issue still persists with more details on the request and response

**Closed by chsriniv9** 2018-08-07 13:24 UTC
Labels: not a issue
