### ISSUE TITLE
I don't see a way to use the Akamai transaction URLs in the SDK

### ISSUE THREAD

**Issue by pjcvijay** [AuthorizeNet/sdk-php#61] opened 2015-07-21 06:12 UTC
I received "Important Authorize.Net Networking Change" email today:

http://app.payment.authorize.net/e/es.aspx?s=986383348&e=913189&elq=aeac1910433b4fd7af65680cda3d5e0e

But how do I send AIM transactions to "https://secure2.authorize.net/gateway/transact.dll" URL using the official SDK?

Thanks!

**Comment by joeydi** [comment] 2015-07-22 17:21
The AIM transaction URL is located in [/lib/AuthorizeNetAIM.php](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/AuthorizeNetAIM.php#L45)

Presumably you can just update that URL to https://**secure2**.authorize.net/gateway/transact.dll

However, I would prefer not to modify this library directly. Will there be an update that references the new Akamai transaction URLs?

**Comment by justbeez** [comment] 2015-07-22 18:15
FYI, this is a duplicate of issue https://github.com/AuthorizeNet/sdk-php/issues/60

**Comment by brianmc** [comment] 2015-07-24 07:06
Closing this as a duplicate of #60 .

This update is coming soon, I do want to assure you that the current URLs are working and will continue to work.

Thanks,

Brian

**Closed by brianmc** 2015-07-24 07:06 UTC

**Comment by pjcvijay** [comment] 2015-07-24 08:42
Thank you, Brian!
