### ISSUE TITLE
namespace warning : xmlns: URI is not absolute

### ISSUE THREAD

**Issue by itecedor** [AuthorizeNet/sdk-php#135] opened 2016-05-17 20:20 UTC
On php7 working to implement the sdk at 1.8.8, I keep seeing these errors:

`Message: simplexml_load_string(): namespace warning : xmlns: URI AnetApi/xml/v1/schema/AnetApiSchema.xsd is not absolute
File: /vendor/authorizenet/authorizenet/lib/shared/AuthorizeNetXMLResponse.php
Line: 29`

Looking at AuthorizeNetXMLResponse.php, I see it's loading in the response xml object. I'm pointing to the sandbox right now, will the same errors happen when I point to production? Or is there something I forgot to set up somewhere?

**Comment by ashtru** [comment] 2016-05-18 04:11
Hi @itecedor Are you getting expected response for your request? 
Because, it only seems to be a warning on client(sdk) side, the response from server should not fail in production, assuming you are getting appropriate response in sandbox.

**Comment by itecedor** [comment] 2016-05-18 14:09
@ashtru the XML response that comes back from the server says that my request completed successfully. But my code does not finish executing correctly because it fails when that error is thrown from the SDK.

I've gone into the sdk files where this error is thrown and changed the code to exclude these warnings by doing:

```simplexml_load_string($response,'SimpleXMLElement', LIBXML_NOWARNING);```

And then I have no errors and my operation completes successfully.

I'm happy to send these changes up as a patch if you want, but I'm wondering why others are not seeing these errors?

**Comment by itecedor** [comment] 2016-05-18 15:13
Here's a sample response XML doc that's generating this problem:

```
<?xml version="1.0" encoding="utf-8"?>
<createCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
  <messages>
    <resultCode>Ok</resultCode>
    <message>
      <code>I00001</code>
      <text>Successful.</text>
    </message>
  </messages>
  <customerProfileId>40752826</customerProfileId>
  <customerPaymentProfileIdList>
    <numericString>37026189</numericString>
  </customerPaymentProfileIdList>
  <customerShippingAddressIdList />
  <validationDirectResponseList>
    <string>1,1,1,(TESTMODE) This transaction has been approved.,000000,P,0,none,Test transaction for ValidateCustomerPaymentProfile.,1.00,CC,auth_only,3,Stephen,Urkel,,123 Fake Street Apt 3,Salem,NJ,28112,US,,,notreal@hotmail.com-sc,,,,,,,,,0.00,0.00,0.00,FALSE,none,4EE452CA9CED3D426E6559CECB8BA1DD,,,,,,,,,,,,,XXXX1881,Visa,,,,,,,,,,,,,,,,</string>
  </validationDirectResponseList>
</createCustomerProfileResponse>
```

So yes, the operation succeeded on the server.

The problem section is `xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"`. Without the `LIBXML_NOWARNING` flag on the xml parser, PHP throws this error.

I've tried changing the php error_reporting all the way to E_ERROR and the error is still thrown and stops the process.

Please advise what I should do, thank you.

**Comment by itecedor** [comment] 2016-05-18 15:58
Another update:

Sometimes the same unit test passes because the XML response has no relative URLs in it. Here's one I just got that passed with no errors:

```
<?xml version="1.0" encoding="utf-8"?>
<createCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
  <messages>
    <resultCode>Ok</resultCode>
    <message>
      <code>I00001</code>
      <text>Successful.</text>
    </message>
  </messages>
  <customerProfileId>40753031</customerProfileId>
  <customerPaymentProfileIdList>
    <numericString>37026375</numericString>
  </customerPaymentProfileIdList>
  <customerShippingAddressIdList />
  <validationDirectResponseList>
    <string>1,1,1,(TESTMODE) This transaction has been approved.,000000,P,0,none,Test transaction for ValidateCustomerPaymentProfile.,1.00,CC,auth_only,3,Stephen,Urkel,,123 Fake Street Apt 3,Salem,NJ,28112,US,,,nea114f0494@hotmail.com-sc,,,,,,,,,0.00,0.00,0.00,FALSE,none,4EE452CA9CED3D426E6559CECB8BA1DD,,,,,,,,,,,,,XXXX1881,Visa,,,,,,,,,,,,,,,,</string>
  </validationDirectResponseList>
</createCustomerProfileResponse>
```

Maybe some, but not all, sandbox servers are returning bad XML?

**Comment by itecedor** [comment] 2016-05-18 16:23
Deleted my last comment because it turns out the old version of the authnet SDK we were using had been hacked to fix this issue. Here's what our old developer had added to the AuthorizeNetXMLResponse.php __construct():

```
        /**
         * Hack to suppress SimpleXML errors caused by ANet's invalid XMLNS.
         */

        $response = str_replace('xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"', '', $response);
```

**Comment by edillingham** [comment] 2017-06-14 18:29
Is this going to be corrected any time soon?  I can't exactly hack the library seeing as it's installed via composer as part of our build process.

**Comment by pdbreen** [comment] 2017-06-14 18:39
Actually, composer & git make it really easy to "hack" - er, patch the library when needed.

1. Create a fork of the library
1. Update the forked version of the library as needed, committing changes back to your github fork
1. Update your composer.json file to include your fork in the repositories section, for example
```
    "repositories": [{
        "type": "vcs",
        "url": "https://github.com/pdbreen/name-of-forked-repo.git"
    }]
```
4. Update your composer.json to use dev@dev-master as the version for the package you updated
5. Optional - send pull request back to original repo so repair is incorporated in next release

**Comment by adavidw** [comment] 2017-06-14 18:40
The actual `xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd` string is returned in the response from the XML web services API itself, so it's probably not going to change any time soon. That's in the response before the SDK even receives the response. However, we can definitely look at something we can do within the SDK to suppress errors, or incorporating someone else's patch to clean it up.

**Comment by gnongsie** [comment] 2018-10-23 09:22
Hi all,

This issue is not reproducible in the latest version 1.9.8. I'm closing this issue for now.

Kindly reopen if the issue persists.

**Closed by gnongsie** 2018-10-23 09:22 UTC
