### ISSUE TITLE
PEM file used for CA validation doesn't work on sandbox, and would be better if made configurable.

### ISSUE THREAD

**Issue by cwilsontv** [AuthorizeNet/sdk-php#298] opened 2018-03-23 14:06 UTC
https://community.developer.authorize.net/t5/Integration-and-Testing/SSL-Certificate-Problem-Another-Authorize-net-Outage/td-p/62246

Apitest.authorize.net has a new SSL as of 3/20 that doesn't validate with this CA: https://github.com/AuthorizeNet/sdk-php/blob/master/lib/ssl/cert.pem

Of course fixing it might break production.

It would be better to alter it so that 
https://github.com/AuthorizeNet/sdk-php/blob/60cf943cc68772e01164d527c47a8f7f394ab0d6/lib/net/authorize/util/HttpClient.php#L80 used a configurable file path instead of the hard coded path. Then this can be updated in the future without needing to make code changes.

It would also allow for the production and development to use different CAs for when things like this happen.

**Comment by frankieb137** [comment] 2018-03-23 15:04
You're the man! Thank you. I followed your links for context, but simply commenting out line 80 in **/authorizenet/authorizenet/lib/net/authorize/util/HttpClient.php**  did the trick.

I also submitted a ticket yesterday with authorizenet developers so I'll provide any new insight when given. Life saver!!

**Comment by cwilsontv** [comment] 2018-03-23 15:18
What environment are you developing in? That fix probably relies on how CURL was built. It doesn't work for me locally on windows.

**Comment by frankieb137** [comment] 2018-03-23 15:29
I'm working locally on a Mac via MAMP. 

developer@authorize.net got back to me just now by the way. They linked me here as well: https://community.developer.authorize.net/t5/Integration-and-Testing/SSL-Certificate-Problem-Another-Authorize-net-Outage/m-p/62281#M36637

Although commenting out line 80 worked, I decided to take their advice and just replace the certs. Works like a charm now as well.

**Comment by cwilsontv** [comment] 2018-03-23 15:34
Okay, that's consistent with what I read on CURL's website:
> (iOS and macOS only) ... If the option is not set, then curl will use the certificates in the system and user Keychain to verify the peer, which is the preferred method of verifying the peer's certificate chain.

**Comment by SmellyFish** [comment] 2018-03-24 21:29
+1

**Comment by ashtru** [comment] 2018-03-24 21:59
Thanks for raising the issue, @cwilsontv  and apologies for the inconvenience faced @frankieb137  @SmellyFish .

This issue was caused by change in the certificate used for verification by the API endpoint. You can replace the .../lib/ssl/cert.pem with the latest **[cert.pem](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/ssl/cert.pem).**

The issue has been fixed in latest release of the **SDK (version [ 1.9.6](https://github.com/AuthorizeNet/sdk-php/tree/))** . Upgrading to it will also resolve the issue.


_Join the [Authorize.Net developer forum](https://community.developer.authorize.net/) to keep abreast with latest features and contribute ideas.
Thanks
Ashutosh_

**Comment by ashtru** [comment] 2018-03-26 06:32
Closing this issue. Please reopen in case of any queries.

**Closed by ashtru** 2018-03-26 06:32 UTC
