### ISSUE TITLE
v1.9.5 i not working with earlier versions of php 7.1

### ISSUE THREAD

**Issue by mhtpg** [AuthorizeNet/sdk-php#292] opened 2018-03-10 21:58 UTC
Hello,

It is stated as package version 1.9.5 requires php version >=5.6.

Bu it's dependant module's(goetas-webservices/xsd2php-runtime: ^0.2.2) dependant module's (jms/serializer: ^1.2) dependant module (doctrine/annotations: ^1.0) requires php: ^7.1

Is there anyone able to run this package on 7.1 > php version >= 5.6 as stated ?

**Comment by kikmak42** [comment] 2018-03-14 07:14
Hi,

The sdk is working with PHP 5.6, as you see in the below travis job
https://travis-ci.org/AuthorizeNet/sdk-php/jobs/352971556

its using

- goetas-webservices/xsd2php-runtime (v0.2.7)
- jms/serializer (1.11.0)
- doctrine/annotations (v1.4.0)

with Composer version 1.6.3

**Comment by ashtru** [comment] 2018-03-26 07:14
Hi @mhtpg , were you able to run the SDK on PHP 5.6 ?

I have run it frequently on PHP 5.6.30 on Windows 10 . 
Perhaps re-cloning and a composer update will help?

**Comment by gcivicodev** [comment] 2018-05-03 23:04
PHP version 5.6
Composer version 1.6.3

**Parse error:** syntax error, unexpected ':', expecting ';' or '{' in **/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php** on line **50**

This is the line 50 on AnnotationRegistry.php
```
50    public static function reset() : void
51    {
52        self::$autoloadNamespaces = [];
53        self::$loaders            = [];
54        self::$failedToAutoload   = [];
55    }
```
composer.json file in /doctrine/annotations/
```
    "name": "doctrine/annotations",
    "require": {
        "php": "^7.1", <============ I think this is the problem.
        "doctrine/lexer": "1.*"
    },
```

Why the SDK can run on `"php": ">=5.6"` but some of its dependencies (like doctrine/annotations) can't?

**So, how can I use the SDK on PHP version 5.6?**

**Comment by mhtpg** [comment] 2018-05-15 11:05
@gcivicodev That's exactly the problem I was facing of.
@ashtru I had to upgrade php to version 7.2

**Comment by ashtru** [comment] 2018-05-30 10:51
Thanks for the detailed information @gcivicodev . You were right about the php 7.1 being wrong version for doctrine/annotations to use. It is mostly likely because the composer was run with PHP version higher than 5.6.

This issue can happen when the vendor folder is generated by **running  composer update on a system with different PHP version**, and then trying to reuse the same vendor folder on a server running different PHP version. The same library will generate a different vendor\ output based, as **composer determines dependencies** based on the PHP version of the system it is running on. Refer: https://github.com/AuthorizeNet/sample-code-php/issues/99 

@mhtpg @gcivicodev  **Can you confirm that the same PHP version is used for generating the vendor folder, and running the code?** Also, run the composer update again if you have recently changed the version.

**Issue reproduction:** I ran composer update with PHP-7.2 and then copied that vendor folder into a new system with PHP 5.6 . On trying to run a charge-credit-card sample, I got the following error:
```
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in C:\Users
\asinghma\Downloads\git\AuthorizeNet\sdk-php\vendor\doctrine\annotations\lib\Doc
trine\Common\Annotations\AnnotationRegistry.php on line 50

Parse error: syntax error, unexpected ':', expecting ';' or '{' in C:\Users\asin
ghma\Downloads\git\AuthorizeNet\sdk-php\vendor\doctrine\annotations\lib\Doctrine
\Common\Annotations\AnnotationRegistry.php on line 50

```
When running the `composer update `again on the 5.6 system, this error got resolved.

**Note:** This issue is not related to the version of Authorize.NET SDK, rather the PHP version used to run composer.

**Comment by chsriniv9** [comment] 2018-06-21 08:34
Based on @ashtru post above, closing this issue. Please feel free to re-open if you are still facing the issue.

**Closed by chsriniv9** 2018-06-21 08:34 UTC
Labels: help-wanted, not a issue
