### ISSUE TITLE
Cannot use "parent" when current class scope has no parent

### ISSUE THREAD

**Issue by KhanhTranJBI** [AuthorizeNet/sdk-php#397] opened 2020-08-30 02:27 UTC
I am using PHP v7.4.4 with `authorizenet/authorizenet` v2.0.0 and got these errors, please fix the issues or how to get around these errors, thanks!

`<b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/MerchantAuthenticationType.php</b> on line <b>291</b><b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/CreditCardSimpleType.php</b> on line <b>100</b><b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/PaymentType.php</b> on line <b>263</b><b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/NameAndAddressType.php</b> on line <b>262</b><b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/CustomerPaymentProfileBaseType.php</b> on line <b>100</b><b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/ANetApiRequestType.php</b> on line <b>129</b><b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/ANetApiResponseType.php</b> on line <b>127</b><b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/MessagesType.php</b> on line <b>134</b><b>Unknown</b>: Cannot use "parent" when current class scope has no parent in <b>/vagrant/zeus/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/MessagesType/MessageAType.php</b> on line <b>97</b>`

**Comment by AllCdnBoy** [comment] 2020-09-06 07:26
yea, same problem.  Trying to move my application to a new server and coming across the same error.

**Comment by KhanhTranJBI** [comment] 2020-09-06 20:11
@AllCdnBoy Please let me know when you have a fix for this issue, thanks!

**Comment by AllCdnBoy** [comment] 2020-09-06 23:43
I replaced my 
"authorizenet/authorizenet": "2.0", 
with 
"authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"
and it's working now.

**Comment by KhanhTranJBI** [comment] 2020-09-07 05:53
@AllCdnBoy I tried it but composer requires token.

Here what I see in the terminal:
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+zeus+2020-09-06+2252
to retrieve a token. It will be stored in "/home/vagrant/.config/composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by KhanhTranJBI** [comment] 2020-09-07 06:10
@AllCdnBoy dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c is working. Even though, it is working but `dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c` is private repo so I am looking for a real package version likes 2.1. Please let me know when that happens, thanks!

**Comment by AllCdnBoy** [comment] 2020-09-07 06:18
Don't hold your breath.  This was a reported issue 9 months ago and there haven't been any updates to the repo in 2 years.  I've been working with Authorize.net for a client for 6 years and they are very antiquated.  I don't expect an update anytime soon.

**Comment by KhanhTranJBI** [comment] 2020-09-08 05:22
@AllCdnBoy I see, thanks!

**Comment by sentiasa** [comment] 2020-09-09 22:53
Same here. When I use it in a queue'd job, it throws me this error; but when I use it in run-time it works fine (with php 7.2)

**Comment by mdasiff** [comment] 2020-09-18 09:06
I think its an old library and many php functions are deprecated, getting the same issue, im using
php .7.2
laravel 6
"authorizenet/authorizenet": "^2.0",

**Comment by aetikon** [comment] 2020-09-24 19:06
Same problem here using php 7.4.

**Comment by buffalobrain** [comment] 2020-10-16 17:45
Same problem. Hoping this repo gets some more attention.

**Comment by rekliner** [comment] 2020-10-26 07:31
Same here.  
php 7.4
"authorizenet/authorizenet": "^2.0",
Codeigniter 3.

Does authorize.net not care about transactions from php backends anymore?  
Where is all their money coming from that they would abandon this repository?

**Comment by multicore-association** [comment] 2020-11-11 00:11
> I replaced my
> "authorizenet/authorizenet": "2.0",
> with
> "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"
> and it's working now.

Where did you replace this? In a file? what file. Sorry I am confused, having the same issue

**Comment by multicore-association** [comment] 2020-11-11 00:12
@AllCdnBoy Where did you replace this "authorizenet/authorizenet": "2.0"?
In a file? what file. Sorry I am confused, having the same issue...

**Comment by AllCdnBoy** [comment] 2020-11-11 00:16
This is in my composer file.  I replaced the original authorize.net package with the dev package.

**Comment by christian-manrique** [comment] 2020-11-11 20:15
Am in shock with this am running with the same issue. Authorize.net is not longer maintenancing this repo? our brands are running daily several transactions which are paid and they are not supporting the php backend?

**Comment by AllCdnBoy** [comment] 2020-11-11 20:20
This is a common theme amongst these processors.  I'm running into the exact same problem with Moneris

**Comment by christian-manrique** [comment] 2020-11-11 20:33
@AllCdnBoy thank you palm! your hotifix works like a charm!

**Comment by edalzell** [comment] 2020-11-11 22:30
> I replaced my
> "authorizenet/authorizenet": "2.0",
> with
> "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"
> and it's working now.

Which PR is this commit from?

Also, unrelated...imagine me coming all this way to find @AllCdnBoy who's from the same place I am!

**Comment by edalzell** [comment] 2020-11-12 01:58
Unfortunately, I get an error when I do that:
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/6069653/98885791-848c5780-2447-11eb-9e6d-481849ec6aa9.png">

@christian-manrique how did you add it?

**Comment by multicore-association** [comment] 2020-11-12 16:53
What Branch do you use? Master?

**Comment by edalzell** [comment] 2020-11-12 16:56
> What Branch do you use? Master?

I copied it exactly as above into my `composer.json` and ran `composer update`

**Comment by multicore-association** [comment] 2020-11-12 17:25
Sorry for being dense, but when I add the line in the require section, it complains:
[RuntimeException]
  Root package 'authorizenet/authorizenet' cannot require itself in its composer.json
  Did you accidentally name your root package after an external package?
if I remove the first line with the "name" then I get this:
Install of authorizenet/authorizenet failed
  [RuntimeException]
  Failed to clone git@github.com:AuthorizeNet/sdk-php.git, git was not found, check that it is installed and in your
  PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.
Here is my composer file:
{
    "type": "library",
    "description": "Official PHP SDK for Authorize.Net",
    "keywords": ["authorizenet", "authorize.net", "payment", "ecommerce"],
    "license": "proprietary",
    "homepage": "http://developer.authorize.net",
    "require": {
        "php": ">=5.6",
        "ext-curl": "*",
        "ext-json": "*",
		"authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"    
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpmd/phpmd": "~2.0"
    },
    "autoload": {
        "classmap": ["lib"]
    },
    "autoload-dev": {
        "classmap": ["tests"]
    }   
}
Thank you for your help!

**Comment by edalzell** [comment] 2020-11-12 17:34
You put that line in your projects `composer.json`.

**Comment by christian-manrique** [comment] 2020-11-12 20:15
> Sorry for being dense, but when I add the line in the require section, it complains:
> [RuntimeException]
> Root package 'authorizenet/authorizenet' cannot require itself in its composer.json
> Did you accidentally name your root package after an external package?
> if I remove the first line with the "name" then I get this:
> Install of authorizenet/authorizenet failed
> [RuntimeException]
> Failed to clone [git@github.com](mailto:git@github.com):AuthorizeNet/sdk-php.git, git was not found, check that it is installed and in your
> PATH env.
> 'git' is not recognized as an internal or external command,
> operable program or batch file.
> Here is my composer file:
> {
> "type": "library",
> "description": "Official PHP SDK for Authorize.Net",
> "keywords": ["authorizenet", "authorize.net", "payment", "ecommerce"],
> "license": "proprietary",
> "homepage": "http://developer.authorize.net",
> "require": {
> "php": ">=5.6",
> "ext-curl": "_", "ext-json": "_",
> "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"
> },
> "require-dev": {
> "phpunit/phpunit": "~4.0",
> "phpmd/phpmd": "~2.0"
> },
> "autoload": {
> "classmap": ["lib"]
> },
> "autoload-dev": {
> "classmap": ["tests"]
> }
> }
> Thank you for your help!

Hey there, try to upgrade php version to at least 7.2, then remove the "authorizenet/authorizenet" package from your composer.json, then remove all vendor folder and run "composer install", once you composer ran successfully try to add the package through CLI i mean "composer require authorizenet/authorizenet". Once the .net package is installed update the composer.json to "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c" and then hit composer update authorizenet/authorizenet

**Comment by degive** [comment] 2020-11-13 00:29
Thanks for your help but it did not work either, I keep getting this message when run the update with the "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c" 

 Install of authorizenet/authorizenet failed
  [RuntimeException]
  Failed to clone git@github.com:AuthorizeNet/sdk-php.git, git was not found, check that it is installed and in your
  PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by edalzell** [comment] 2020-11-13 00:30
What, exactly, are you doing?

Can we see your `composer.json`?

**Comment by degive** [comment] 2020-11-13 00:32
here it is:
{
    "type": "library",
    "description": "Official PHP SDK for Authorize.Net",
    "keywords": ["authorizenet", "authorize.net", "payment", "ecommerce"],
    "license": "proprietary",
    "homepage": "http://developer.authorize.net",
    "require": {
        "php": ">=5.6",
        "ext-curl": "*",
        "ext-json": "*",
		"authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"    
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpmd/phpmd": "~2.0"
    },
    "autoload": {
        "classmap": ["lib"]
    },
    "autoload-dev": {
        "classmap": ["tests"]
    }   
}

**Comment by edalzell** [comment] 2020-11-13 00:33
That's the wrong composer.json. You're supposed to be editing your project's composer.json NOT package's.

**Comment by degive** [comment] 2020-11-13 00:50
so what exactly has to be in this composer.json file?

thank you for your help.

**Comment by degive** [comment] 2020-11-13 01:22
I just ran it with this in the composer.json file and got the same error. Do you think it is my environment that is screwed up?
{
  "require": {
  "php": ">=5.6",
  "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"    
  }
}

**Comment by edalzell** [comment] 2020-11-13 01:34
Which composer.json are you putting this in? Show us the path please.

**Comment by degive** [comment] 2020-11-13 16:56
I am using the following composer.json and run "composer update" from the path where my authorize.net api is.
{
"require": {
"php": ">=5.6",
"authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"
}
}

and then I get this error:
[RuntimeException]
Failed to clone git@github.com:AuthorizeNet/sdk-php.git, git was not found, check that it is installed and in your
PATH env.
'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by degive** [comment] 2020-11-13 19:57
I am able to update to 2.0 but not "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c", I think it must have been removed...

**Comment by degive** [comment] 2020-11-14 00:14
I just tried this from a different computer and got the same error, I think this git is gone. If you have a working copy, could you tar or zip it and email it to me please? micheldegive@gmail.com. Thank you.

**Comment by david-m-sitation** [comment] 2020-11-16 16:01
Okay, so here's a question I think is worth asking.

If we're using an abandoned development branch to get around a full-on bug, what guarantees do we have that this development branch is using secure methods? Clearly regression testing isn't being done on the master branch for core functionality, so is it even _safe_ to use this package? Especially considering this is an SDK for handling sensitive credit card information?

Is there any _good_ reason aside from maybe cost for me to use this package instead of Stripe? I mean, Stripe has a ton of verified integrations and they're modern. And their core PHP functionality isn't broken.

**Comment by mbiang** [comment] 2020-12-03 15:48
So is this package basically dead?  No PHP 7.4 support?  Does anyone have any recommendations for another library for Authorize.net, or do I basically have to roll my own?

**Comment by edalzell** [comment] 2020-12-03 16:03
I've got this in my `composer.json` and it works. This is the reference to the PR that adds this. Plan on forking so it won't go away.

```
        "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c",
```

**Comment by christian-manrique** [comment] 2020-12-03 16:08
@mbiang hey there, what it said @edalzell is correct on my end works as well, i was running with weird responses using master branch but i changed my composer.json on the require block by "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c", then i ran the composer install command removing that all the folder vendor/authorizenet and that works pretty well, your application should be good doing those changes

**Comment by david-m-sitation** [comment] 2020-12-03 17:39
Just confirming what everyone else has been saying. Using the dev branch specified above will get you what you need.

It's really telling that Visa/Authorize.net are just giving up since Stripe and other providers are much more frequently used. Which is sad, because Authorize.net would probably be used more if they had an SDK that didn't immediately break your project upon download from the master branch.

**Comment by edalzell** [comment] 2020-12-04 03:17
> Plan on forking so it won't go away.

Alright, I forked it and pull the PR into a branch to make it easier to get. Add `https://github.com/silentzco/sdk-php` as a `vcs` repo in your composer and require `"authorizenet/authorizenet": "dev-php-74",`.

**Comment by rickmacgillis** [comment] 2020-12-22 02:57
I fixed @kikmak42's disaster code that caused this. Why he didn't just use a Trait is beyond me, but I'll digress. Anyway, if you don't feel like dealing with fixing it, I did it as a file search and replace in Eclipse and you can grab the fixed version at https://github.com/rickmacgillis/authnet-sdk-php

I decided not to add it to Packagist as I'm not planning to maintain my fixed copy. So you can either fork my repo or add the following code to your composer.json.

```
	"repositories" : [{
		"type" : "vcs",
		"url" : "git@github.com:rickmacgillis/authnet-sdk-php.git"
	}]
```

**Comment by samoldenburg** [comment] 2021-01-04 17:27
> Okay, so here's a question I think is worth asking.
> 
> If we're using an abandoned development branch to get around a full-on bug, what guarantees do we have that this development branch is using secure methods for payment processing? Clearly regression testing isn't being done on the master branch for core functionality, so is it even _safe_ to use this package? Especially considering this is an SDK for handling sensitive credit card information?
> 
> Is there any _good_ reason aside from maybe cost for me to use this package instead of Stripe? I mean, Stripe has a ton of verified integrations and they're modern. And their core PHP functionality isn't broken.
> 
> Edit: *I'm also asking these questions out of actual ignorance - I'm more than happy if I'm just being heckin' paranoid :)

You are correct to be paranoid. This is a credit card processing SDK, any suggestions people have made indicating people should point to a development branch are incredibly misguided and indeed, outright dangerous.

I unfortunately ended up using this SDK as we had a business requirement to use authorize.net. I regret not developing my own API integration on the back end, I did not realize that this package had not received a new release in literally years. The package being broken in PHP 7.4 for this long, for such an easy thing to resolve, proves to me that this package is abandoned.

Unfortunately for me, the easiest, and safest solution was to create a private clone of the repository, and apply the fix myself. I can then just set my composer.json file to a new version that I've released with the patches applied myself.  Locking to a specific version in someone else's fork would have worked as well, but I felt safer being in full control of the code, and I wouldn't have to worry about some other developer potentially messing with the composer settings and allowing future updates from that fork to potentially get introduced into the code base.

**Comment by degive** [comment] 2021-01-04 17:29
I switched over to Stripe. Love it. So much better than authorize.net!

**Comment by rekliner** [comment] 2021-01-04 20:16
@degive, I wish I could switch to Stripe as well but it's unfortunately a business requirement and client's account for me too.

And that's about the most official notice of abandonment we can expect:  They aren't even going to moderate an endorsement for their more modern competitor here.  Even their PR is uninvested!
¯\_(ツ)_/¯

**Comment by alexey-rakul** [comment] 2021-01-18 18:49
> > Plan on forking so it won't go away.
> 
> Alright, I forked it and pull the PR into a branch to make it easier to get. Add `https://github.com/silentzco/sdk-php` as a `vcs` repo in your composer and require `"authorizenet/authorizenet": "dev-php-74",`.

Thank you! This fixed the issue with parent::

**Comment by ashleyfae** [comment] 2021-02-17 17:24
Just noting that this is a fatal error in PHP 8.

**Comment by cgowez** [comment] 2021-02-23 00:40
Hi, I am getting same error using PHP v7.4.4 with authorizenet/authorizenet v2.0.1.
I tried with _"authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"_, but it couldn't be found, is there another way to fix it?

Thanks.

**Comment by cgowez** [comment] 2021-02-25 00:21
> > Okay, so here's a question I think is worth asking.
> > If we're using an abandoned development branch to get around a full-on bug, what guarantees do we have that this development branch is using secure methods for payment processing? Clearly regression testing isn't being done on the master branch for core functionality, so is it even _safe_ to use this package? Especially considering this is an SDK for handling sensitive credit card information?
> > Is there any _good_ reason aside from maybe cost for me to use this package instead of Stripe? I mean, Stripe has a ton of verified integrations and they're modern. And their core PHP functionality isn't broken.
> > Edit: *I'm also asking these questions out of actual ignorance - I'm more than happy if I'm just being heckin' paranoid :)
> 
> You are correct to be paranoid. This is a credit card processing SDK, any suggestions people have made indicating people should point to a development branch are incredibly misguided and indeed, outright dangerous.
> 
> I unfortunately ended up using this SDK as we had a business requirement to use authorize.net. I regret not developing my own API integration on the back end, I did not realize that this package had not received a new release in literally years. The package being broken in PHP 7.4 for this long, for such an easy thing to resolve, proves to me that this package is abandoned.
> 
> Unfortunately for me, the easiest, and safest solution was to create a private clone of the repository, and apply the fix myself. I can then just set my composer.json file to a new version that I've released with the patches applied myself. Locking to a specific version in someone else's fork would have worked as well, but I felt safer being in full control of the code, and I wouldn't have to worry about some other developer potentially messing with the composer settings and allowing future updates from that fork to potentially get introduced into the code base.

Hi @samoldenburg , can you share your fix so I can apply it as you did? I haven't found a way to make it work and I have no choice to use another payment provider.
Hope you can, thanks.

**Comment by samoldenburg** [comment] 2021-02-25 03:56
> > > Okay, so here's a question I think is worth asking.
> > > If we're using an abandoned development branch to get around a full-on bug, what guarantees do we have that this development branch is using secure methods for payment processing? Clearly regression testing isn't being done on the master branch for core functionality, so is it even _safe_ to use this package? Especially considering this is an SDK for handling sensitive credit card information?
> > > Is there any _good_ reason aside from maybe cost for me to use this package instead of Stripe? I mean, Stripe has a ton of verified integrations and they're modern. And their core PHP functionality isn't broken.
> > > Edit: *I'm also asking these questions out of actual ignorance - I'm more than happy if I'm just being heckin' paranoid :)
> > 
> > 
> > You are correct to be paranoid. This is a credit card processing SDK, any suggestions people have made indicating people should point to a development branch are incredibly misguided and indeed, outright dangerous.
> > I unfortunately ended up using this SDK as we had a business requirement to use authorize.net. I regret not developing my own API integration on the back end, I did not realize that this package had not received a new release in literally years. The package being broken in PHP 7.4 for this long, for such an easy thing to resolve, proves to me that this package is abandoned.
> > Unfortunately for me, the easiest, and safest solution was to create a private clone of the repository, and apply the fix myself. I can then just set my composer.json file to a new version that I've released with the patches applied myself. Locking to a specific version in someone else's fork would have worked as well, but I felt safer being in full control of the code, and I wouldn't have to worry about some other developer potentially messing with the composer settings and allowing future updates from that fork to potentially get introduced into the code base.
> 
> Hi @samoldenburg , can you share your fix so I can apply it as you did? I haven't found a way to make it work and I have no choice to use another payment provider.
> Hope you can, thanks.

I applied the same fix as https://github.com/rickmacgillis/authnet-sdk-php, but put it under a private repo for security purposes.

**Comment by bridgesense** [comment] 2021-03-26 20:01
> Hi, I am getting same error using PHP v7.4.4 with authorizenet/authorizenet v2.0.1.
> I tried with _"authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"_, but it couldn't be found, is there another way to fix it?
> 
> Thanks.

Try the following changes to composer.  This is processing payments for me on 7.4.  They're doing great work with this patch.  Hopefully it gets released into the wild soon.

`
"authorizenet/authorizenet": "dev-php-version-upgrade"
`

**Comment by iaroslavglodov** [comment] 2021-03-29 08:10
> I replaced my
> "authorizenet/authorizenet": "2.0",
> with
> "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"
> and it's working now.

Seems not working anymore.
`Failed to execute git checkout 'ef297d3e2d7c1092ddabd2c376eb485aac1aa66c'` after running `composer update`
Composer cannot find this commit. Even after removing `vendor/` folder.

**Comment by bridgesense** [comment] 2021-03-29 16:13
> > I replaced my
> > "authorizenet/authorizenet": "2.0",
> > with
> > "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"
> > and it's working now.
> 
> Seems not working anymore.
> `Failed to execute git checkout 'ef297d3e2d7c1092ddabd2c376eb485aac1aa66c'` after running `composer update`
> Composer cannot find this commit. Even after removing `vendor/` folder.

That commit appears to have been removed.  There is another branch dedicated to this issue.

**Comment by iaroslavglodov** [comment] 2021-04-01 06:06
> > > I replaced my
> > > "authorizenet/authorizenet": "2.0",
> > > with
> > > "authorizenet/authorizenet": "dev-master#ef297d3e2d7c1092ddabd2c376eb485aac1aa66c"
> > > and it's working now.
> > 
> > 
> > Seems not working anymore.
> > `Failed to execute git checkout 'ef297d3e2d7c1092ddabd2c376eb485aac1aa66c'` after running `composer update`
> > Composer cannot find this commit. Even after removing `vendor/` folder.
> 
> That commit appears to have been removed. There is another branch dedicated to this issue.

Found another working branch `dev-php-version-upgrade`, so my composer.json looks like:
```json
{
	"require": {
		"authorizenet/authorizenet": "dev-php-version-upgrade"
	}
}
```
And it works!

**Comment by avibhatt1** [comment] 2021-04-08 05:56
just update your version 2.0 to 2.0.2 
example :
 "require": {
        "authorizenet/authorizenet": "2.0.2",
}

**Comment by rekliner** [comment] 2021-04-08 15:05
After all this time Authorize.net has started maintaining this repository again.  Version 2.0.2 was released a few days ago and finally puts this bug to bed.

**Comment by d3solutions** [comment] 2021-05-13 20:10
The commit for version 2.0.2 has not been verified, nor has this release been officially announced.

It may fix the bug, but saying that "Authorize.net has started maintaining this repository again" feels like a stretch.

![Releases_·_AuthorizeNet_sdk-php](https://user-images.githubusercontent.com/786927/118181406-95b12380-b3ec-11eb-9400-5e10b27b23ff.png)

**Comment by gnongsie** [comment] 2024-09-23 05:48
This issue does not appear in the latest version, as evidenced by recent commits and CI runs.
Closing this issue based on this.

**Closed by gnongsie** 2024-09-23 05:48 UTC
